module.exports = {
  AUTH_SERVICE: process.env.AUTH_SERVICE_URL,
  PRODUCT_SERVICE: process.env.PRODUCT_SERVICE_URL,
  CART_SERVICE: process.env.CART_SERVICE_URL,
  ORDER_SERVICE: process.env.ORDER_SERVICE_URL,
  PAYMENT_SERVICE: process.env.PAYMENT_SERVICE_URL,
  NOTIFICATION_SERVICE: process.env.NOTIFICATION_SERVICE_URL,
};
